name: Regression Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu_latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Regression Tests
        run: pytest -m regression

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: reports/


